### ISSUE TITLE
Publish BOSH release when creating a new Github release

### ISSUE THREAD

**Issue by gerhard** [onemedical/datadog-agent-boshrelease#11]
Hi,

Would it be possible to upload the final BOSH release as a tar.gz when you create a new Github release? I would like our Concourse pipeline to pull new BOSH releases straight from Github.

Thank you, Gerhard.

**Comment by adamstegman** [comment]
Sure! Thanks for the suggestion, it's a great idea. I added [v5.8.5.3](https://github.com/onemedical/datadog-agent-boshrelease/releases/tag/v5.8.5.3) and the newly-released [v5.8.5.4](https://github.com/onemedical/datadog-agent-boshrelease/releases/tag/v5.8.5.4)

**Comment by gerhard** [comment]
That's great, thanks. Would you mind including the SHA1 in the release notes so that releases can be consumed remotely, via URL.

**Comment by adamstegman** [comment]
Definitely, just added them.

**Comment by gerhard** [comment]
👍
