### ISSUE TITLE
Time to cut a new final BOSH release?

### ISSUE THREAD

**Issue by gerhard** [onemedical/datadog-agent-boshrelease#12]
There isn't a final release with #8, I find that feature really useful. Currently, we're building dev releases, but would appreciate a final release with this functionality.

**Comment by adamstegman** [comment]
#8 was part of [v5.8.5.3](https://github.com/onemedical/datadog-agent-boshrelease/releases/tag/v5.8.5.3). But #9 and #10 were unreleased, so I cut [v5.8.5.4](https://github.com/onemedical/datadog-agent-boshrelease/releases/tag/v5.8.5.4).

**Comment by gerhard** [comment]
Perfect, thanks!
