### ISSUE TITLE
CentOS stemcell support

### ISSUE THREAD

**Issue by gerhard** [onemedical/datadog-agent-boshrelease#18]
I've discovered today that this release does not support CentOS. Specifically, [python-dev/packaging](https://github.com/onemedical/datadog-agent-boshrelease/blob/master/packages/python-dev/packaging#L9-L12) makes Debian assumptions.

It's not biggie if I'm the only one having this problem, but I was wondering if there is wider interest in making this release CentOS compatible.

**Comment by adamstegman** [comment]
Sorry about that! I skipped the hard work of figuring out how to actually install python.

> This release only supports Ubuntu Trusty stemcells - it uses the python-dev apt package. Packaging requires Internet connectivity - Python packages are downloaded to the install target.

I'd be happy to see this be made into a better-behaving release.

**Comment by gerhard** [comment]
Not a problem, happy to leave it like this for now, was just wondering if this was intentional. Thanks for confirming!
